baseURL = 'https://shadowrocket.ink/'
languageCode = 'en-us'
title = 'shadowrocket'
theme='hugo-book'

# Book configuration
disablePathToLower = true
enableGitInfo = true

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1

[languages]
[languages.zh]
  languageName = 'Chinese'
  contentDir = 'content.zh'
  weight = 1

[languages.en]
  languageName = 'English'
  contentDir = 'content.en'
  weight = 3

[languages.ru]
  languageName = 'Russian'
  contentDir = 'content.ru'
  weight = 2



[[menu.after]]
  name = "20元1000G不限时"
  url = "https://xn--4gqx1hgtfdmt.com/#/register?code=Aqr3awfK"
  weight = 30


[params]
# 黑暗模式
  BookTheme = 'dark'
# 留言板
  BookComments = true
# 翻译
  BookTranslatedOnly = true



